services:
  python:
    build:
      context: ./python/
      dockerfile: Dockerfile
    container_name: gsv_python
    working_dir: /app
    user: root
    depends_on:
      - postgis
    ports:
      - "5100:5000"
    volumes:
      - ./python:/app

  postgis:
    image: postgis/postgis:latest
    container_name: gsv_postgis
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
